spring.application.name=booknest
server.port=8098
spring.profiles.active=dev
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=9efdeaf7369770
spring.mail.password=9b40be847fd067
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

booknest.mail.from=no-reply@booknest.local
booknest.mail.to=contact@booknest.local


